spring.application.name=user-service

spring.datasource.url=jdbc:postgresql://localhost:5432/ecomm
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#jwt.secret=LPqi0te33pkmVOBnXn4kTIfq0s43djOPJ1AMwwx9J8w=
#jwt.expiration=86400000

# JWT secret key
jwt.secret=LPqi0te33pkmVOBnXn4kTIfq0s43djOPJ1AMwwx9J8w=

# Access Token expiration time (e.g., 15 minutes = 15 * 60 * 1000 ms = 900000)
jwt.access-token-expiration=900000

# Refresh Token expiration time (e.g., 7 days = 7 * 24 * 60 * 60 * 1000 ms = 604800000)
jwt.refresh-token-expiration=604800000
