server.port=8082
spring.application.name=product-service
spring.datasource.url=jdbc:postgresql://localhost:5432/ecomm
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# JWT secret key
jwt.secret=LPqi0te33pkmVOBnXn4kTIfq0s43djOPJ1AMwwx9J8w=

# Access Token expiration time (e.g., 15 minutes = 15 * 60 * 1000 ms = 900000)
jwt.access-token-expiration=900000
